version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: result/latest
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - ".:/src"
    environment:
      - JEKYLL_ENV=production

